serviceTree: &serviceTree
  platform: &platform alcohol
  layer: &layer '2'

tags: &tags
  atomi.cloud/platform: *platform
  atomi.cloud/layer: *layer


lithium:
  serviceTree:
    <<: *serviceTree

  tags:
    <<: *tags

  bromine:
    enable: true
    serviceTree:
      <<: *serviceTree
    rootSecret:
      ref:
        clientId: ALCOHOL_LITHIUM_CLIENT_ID
        clientSecret: ALCOHOL_LITHIUM_CLIENT_SECRET
  fullnameOverride: 'lithium-api'

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: 'entei-zinc-letsencrypt-issuer'
    hosts:
      - host: api.lithium.alcohol.lapras.cluster.atomi.cloud
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - api.lithium.alcohol.lapras.cluster.atomi.cloud
        secretName: api-lithium-alcohol-lapras-tls

  adminIngress:
    enabled: false
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: 'entei-zinc-letsencrypt-issuer'

  replicaCount: 2
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 256Mi

  maincache:
    fullnameOverride: 'lithium-maincache'
    storage:
      enabled: false
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 250m

  app:
    endpoint: "https://api.lithium.alcohol.lapras.cluster.atomi.cloud"
    adminEndpoint: "https://admin.lithium.alcohol.lapras.atomi.cloud"
    trustProxyHeader: 1

zinc:
  serviceTree:
    <<: *serviceTree

  bromine:
    enable: true
    target: &target zinc
    serviceTree:
      <<: *serviceTree

  # -- YAML Anchor for PodSecurityContext
  podSecurityContext: &podSecurityContext
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true

  # -- YAML Anchor for SecurityContext
  securityContext: &securityContext
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    capabilities:
      drop:
        - ALL

  xSecurityContext: &migrateSecurityContext
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    capabilities:
      drop:
        - ALL

  api:
    enabled: true
    fullnameOverride: 'zinc-api'
    envFromSecret: *target
    serviceTree:
      <<: *serviceTree
    image:
      repository: ghcr.io/atomicloud/alcohol.zinc/api
    imagePullSecrets: [ ]
    securityContext: *securityContext
    podSecurityContext: *podSecurityContext
    replicaCount: 1

    configMountPath: /app/Config

    service:
      type: ClusterIP
      port: 80
      containerPort: 9050

    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: 'entei-zinc-letsencrypt-issuer'
      hosts:
        - host: api.zinc.alcohol.lapras.cluster.atomi.cloud
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - api.zinc.alcohol.lapras.cluster.atomi.cloud
          secretName: api-zinc-alcohol-lapras-tls

  migration:
    enabled: true
    fullnameOverride: 'zinc-migration'
    envFromSecret: *target
    securityContext: *migrateSecurityContext
    podSecurityContext: *podSecurityContext
    configMountPath: /app/Config

    image:
      repository: ghcr.io/atomicloud/alcohol.zinc/migrate
    serviceTree:
      <<: *serviceTree

  maindb:
    enable: false

  maincache:
    enable: false

  mainstorage:
    enable: false






