version: '3'

env:
  SOS_PROJECT_ID: '1cffa31e-7653-4c0d-9a18-9914a2dbc30b'
  RELEASE_NAME: sulfoxide-gold

includes:
  util: tasks/Taskfile.util.yaml
  base: tasks/Taskfile.cluster.yaml
  pichu:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pichu
  pikachu:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pikachu
  raichu:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: raichu
  # entei:opal:
  #   taskfile: tasks/Taskfile.cluster.yaml
  #   vars:
  #     LANDSCAPE: entei
  #     CLUSTER: opal

tasks:
  # Utility
  start:cluster:
    desc: Starts the playground cluster to test helm charts
    cmds:
      - ./scripts/local/create-k3d-cluster.sh

  stop:cluster:
    desc: Destroys the playground cluster to test helm charts
    cmds:
      - ./scripts/local/delete-k3d-cluster.sh

  # Helm Operations
  update:
    desc: Update Helm dependencies
    dir: chart
    cmds:
      - helm dependency update

  latest:
    desc: Get latest dependencies
    cmds:
      - task: util:latest-oci
        vars:
          NAME: zinc
          OCI: ghcr.io/atomicloud/alcohol.zinc/root-chart
      - task: util:latest-oci
        vars:
          NAME: lithium
          OCI: ghcr.io/atomicloud/aldehyde.lithium/aldehyde-lithium
